services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'


  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/mydatabase -user=myuser -password=secret migrate
    volumes:
      - ./src/main/resources/db/migrations:/flyway/sql
    depends_on:
      - postgres

volumes:
  postgres_database:


