spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret


user:
  password:
    regex: "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*()_+|~-]).{8,}$"