
CREATE TABLE "USER" (
      IDT_USER SERIAL PRIMARY KEY,
      DES_USERNAME VARCHAR(255) UNIQUE NOT NULL,
      DES_PASSWORD VARCHAR(255) NOT NULL,
      DES_EMAIL VARCHAR(255) NOT NULL,
      DAT_CREATED_AT TIMESTAMP,
      DAT_UPDATED_AT TIMESTAMP
);
